import type { Metadata } from "next";
import "./globals.css";
import { defaultFont } from "@/main/utils/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <Favicon />
      </head>
      <body className={`${defaultFont.className} antialiased`}>{children}</body>
    </html>
  );
}

const Favicon = () => {
  return (
    <link
      rel="icon"
      href="https://raw.githubusercontent.com/beepbop-labs/assets/refs/heads/main/beepbop/favicon/favicon.ico"
      sizes="any"
    />
  );
};
